from fastapi import APIRouter
from services.summary_service import get_daily_summary

router = APIRouter(prefix="/api/summary", tags=["AI Summary"])


@router.get("/")
async def fetch_summary():
    """
    Returns today's AI-generated football daily briefing.
    Generated by Gemini 1.5 Flash. Cached for 1 hour.
    """
    summary = await get_daily_summary()
    return summary
